# Generated by Django 3.2.11 on 2022-01-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('userid', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('send_email', models.BooleanField(default=True)),
                ('ischeck', models.BooleanField(default=False)),
            ],
        ),
    ]
