# Generated by Django 3.2.11 on 2022-02-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_default_country'),
        ('checkout', '0039_alter_checkout_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='alternative_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alternative_channel', to='channel.channel'),
        ),
    ]
