# Generated by Django 3.2.11 on 2022-02-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0040_checkout_alternative_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='requested_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
