# Generated by Django 3.2.11 on 2022-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0123_update_order_search_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
